version: "3.8"

services:
  # web:
  #   build: .
  #   restart: always
  #   ports:
  #     - "5000:5000"
  #   command: "flask run"
  #   volumes:
  #     - type: bind
  #       source: ./mnt/flask_log
  #       target: /app/log

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASSWORD=guest

  # worker:
  #   build: .
  #   restart: always
  #   command: "celery -A pgsql_connector worker --loglevel=INFO"
  #   user: nobody
  #   depends_on:
  #     - rabbit
  #     - redis
  #     - web

networks:
  default:
    name: bossruji-network
